---
# tasks file for aarole

- name: aarole FQDN
  command: hostname -f
  register: out

- name: aarole FQDN
  debug: var=out.stdout

- name: aarole IP address
  command: hostname -I
  register: out

- name: aarole IP address
  debug: var=out.stdout

- name: aarole date
  command: date
  register: out

- name: aarole date
  debug: var=out.stdout

