---
# tasks file for echo

- name: myrole03 FQDN
  command: hostname -f
  register: out

- name: myrole03 FQDN
  debug: var=out.stdout

- name: myrole03 IP address
  command: hostname -I
  register: out

- name: myrole03 IP address
  debug: var=out.stdout

- name: myrole03 date
  command: date
  register: out

- name: myrole03 date
  debug: var=out.stdout

